server:
  port: 50001
spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yczbest
    url: jdbc:mysql://localhost:3306/galaxy-usercenter?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&remarks=true&useInformationSchema=true
