server:
  port: 50000 #指定运行端口
spring:
  application:
    name: eureka-server #指定服务名称
  spring:
    application:
      name: eurekaserver
  datasource:
    url: jdbc:mysql:///intelli_galaxy?serverTimezone=UTC
    username: root
    password: yczbest
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  instance:
    hostname: localhost #指定主机地址
  client:
    service-url:
      defaultZone: http://127.0.0.1:50000/eureka/
    fetch-registry: false #指定是否要从注册中心获取服务（注册中心不需要开启）
    register-with-eureka: false #指定是否要注册到注册中心（注册中心不需要开启）
#  server:
#    enable-self-preservation: false #关闭保护模式

